### ISSUE TITLE
Error Installing plugin:  src/android/Snapshot.java not found!

### ISSUE THREAD

**Issue by uscivics** [ezartech/ezar-ionic#5]
I've been able to successfully add the com.ezartech.ezar.videooverlay plugin to a project and use it, but I am not able to get the other plugins added to the project I'm working on.

I've noticed that the videooverlay plugin contains a package.json and the other plugins do not.

I've checked permissions on the files to ensure that cordova could read them. Not sure why this error is occurring. 

Any insight would be appreciated.

This is using the latest ezar-startup-kit downloaded from the website. 0.2.10

Environment Info
----------------------------------------------------------------------------------------------------
`ionic info`

Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.8.6 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v5.10.0
Xcode version: Xcode 8.2.1 Build version 8C1002

//Cordova plugins
----------------------------------------------------------------------------------------------------
`cordova plugins list`

com.ezartech.ezar.videooverlay 0.2.4 "ezAR Video Overlay"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

//FROM within plugins directory where com.ezartech.ezar.snapshot exists...

`cordova plugin add com.ezartech.ezar.snapshot`
and 
`ionic plugin add com.ezartech.ezar.snapshot` 

Both commands return the following errors.
-------------------------------------------------------------------------------------------------
Installing "com.ezartech.ezar.snapshot" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.ezartech.ezar.snapshot':CordovaError: Uh oh!
"/Library/WebServer/Documents/GIT/plugins/com.ezartech.ezar.snapshot/src/android/Snapshot.java" not found!
at copyFile (/Library/WebServer/Documents/GIT/platforms/android/cordova/lib/pluginHandlers.js:219:36)
at copyNewFile (/Library/WebServer/Documents/GIT/platforms/android/cordova/lib/pluginHandlers.js:250:5)
at handlers.source-file.install (/Library/WebServer/Documents/GIT/platforms/android/cordova/lib/pluginHandlers.js:43:17)
at Object.ActionStack.process (/Library/WebServer/Documents/GIT/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
at PluginManager.doOperation (/Library/WebServer/Documents/GIT/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
at PluginManager.addPlugin (/Library/WebServer/Documents/GIT/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
at /Library/WebServer/Documents/GIT/platforms/android/cordova/Api.js:254:18
at _fulfilled (/Library/WebServer/Documents/GIT/platforms/android/cordova/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (/Library/WebServer/Documents/GIT/platforms/android/cordova/node_modules/q/q.js:863:30)
at Promise.promise.promiseDispatch (/Library/WebServer/Documents/GIT/platforms/android/cordova/node_modules/q/q.js:796:13)
Error: Uh oh!
"/Library/WebServer/Documents/GIT/plugins/com.ezartech.ezar.snapshot/src/android/Snapshot.java" not found!

**Comment by wayneparrott** [comment]
See my response on the ezAR forum here: 
https://support.ezartech.com/index.php?p=/discussion/62/errors-installing-ezar-snapshot-and-ezar-facedetector
